### ISSUE TITLE
Can it works with 3Dircadb Dataset?

### ISSUE THREAD

**Issue by Kangjik94** [soribadiaby/Deep-Learning-liver-segmentation-project#2]
i want to do this code with 3Dircadb dataset.
what code i have to put inside?

and what preprocess to do with this dataset?

**Comment by soribadiaby** [comment]
You can use the same code, it should work

**Comment by nikhilgang** [comment]
> i want to do this code with 3Dircadb dataset.
> what code i have to put inside?
> 
> and what preprocess to do with this dataset?

Have you run this code on 3Dircadb dataset? Please share the code to preprocess it

**Comment by nikhilgang** [comment]
> You can use the same code, it should work

Can you explain it a little bit more by sharing the code?
