### ISSUE TITLE
some confused in data.py

### ISSUE THREAD

**Issue by zz10001** [soribadiaby/Deep-Learning-liver-segmentation-project#5]

**Comment by zz10001** [comment]
Hi,@Soriba Diaby
Thanks for your great work,When i read you code in data.py(line42)`if len(np.unique(dimgl))!=1:`
I cannot understand what it means,can you explain it.
Much obligated for your help!

**Comment by zz10001** [comment]
Hi,@soriba\ Diaby
Thanks for your great work,When i read you code in data.py(line42)if len(np.unique(dimgl))!=1:
I cannot understand what it means,can you explain it.
Much obligated for your help!

**Comment by zz10001** [comment]
Hi，
Thanks for your great work,When i read you code in data.py(line42)if len(np.unique(dimgl))!=1:
I cannot understand what it means,can you explain it.
Much obligated for your help!

**Comment by zz10001** [comment]
Hi，
Thanks for your great work,When i read you code in data.py(line42)`if len(np.unique(dimgl))!=1:`
I cannot understand what it means,can you explain it.
Much obligated for your help!

**Comment by soribadiaby** [comment]
Hello, 
is it more understandable with the new version of the code? (I just pushed)

**Comment by zz10001** [comment]
Thanks,i got it!
May you have a nice day!
