### ISSUE TITLE
Source of the 20 CT scans

### ISSUE THREAD

**Issue by chongduan** [soribadiaby/Deep-Learning-liver-segmentation-project#6]
Hi, I used the 20 CT scans with liver masks in my research. What's the best way to acknowledge the source of these data? Thank you!

**Comment by soribadiaby** [comment]
Hi, you can find the data here https://www.ircad.fr/fr/recherche/3d-ircadb-01-fr/

**Comment by chongduan** [comment]
Awesome! Thank you Soriba!
